### PR TITLE
Support class scoped variable lookup in interpolation lambdas

### PR DESCRIPTION
**Pull request by davepeck**
This follows discussion in the discord chat. 

With these changes, the following code works:

```python
def fstr(*args):
    return "".join(arg if isinstance(arg, str) else arg[0]() for arg in args)

class Example:
    food = "burrito"
    v = fstr"neato {food}"  # prior to this branch, NameError here
    
print(Example.v)  # neato burrito
```

Two caveats:

1. I have never before looked at or edited cpython
2. This is almost certainly the wrong approach. (It's a hack. This PR adds a `sees_class_scope` flag to the `Lambda` AST node and later sets the necessary `ste_*` flags in `symtable_visit_expr()`. I assume we never want explicit mentions of scope to creep into the AST!)

To be super clear: I have no expectation that this should be merged. I'd love to hear what the "right" approach actually is. But, this was fun learning for me and hopefully useful for further discussion. 😅

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This looks about right. I guess this means your implementation internally creates `ast.Lambda` nodes for the formatted parts of each tag string, which works as a quick hack but probably wouldn't be what we'd want in the final version. Instead, there should be a new kind of AST node for tag strings, handled specially in the symtable and compiler.

**Comment by davepeck** [comment]
> Instead, there should be a new kind of AST node for tag strings, handled specially in the symtable and compiler.

@JelleZijlstra Got it, thanks. Maybe more along these lines? https://github.com/lysnikolaou/cpython/compare/tag-strings-rebased...davepeck:tagstr-cpython:davepeck/implicit-interpolation-scope

**Comment by JelleZijlstra** [comment]
On a quick look, I think that approach makes sense.

You may also want to think about whether it makes sense to prohibit yield/await/walrus inside interpolations, similar to what we're doing in PEP 695 annotation scopes (some discussion in https://jellezijlstra.github.io/pep695#other-issues).

**Comment by davepeck** [comment]
> some discussion in https://jellezijlstra.github.io/pep695#other-issues

Interesting. And: joy, that looks like it was a bucket of fun.

**Comment by lysnikolaou** [comment]
> I guess this means your implementation internally creates ast.Lambda nodes for the formatted parts of each tag string, which works as a quick hack but probably wouldn't be what we'd want in the final version.

Thanks @JelleZijlstra for having a look at this. This was based on my implementation, which was based on Guido's implementation and is mostly there for experimentation. I was planning to work on doing this correctly next week but @davepeck beat me to it. 🎉 🚀 

> You may also want to think about whether it makes sense to prohibit yield/await/walrus inside interpolations, similar to what we're doing in PEP 695 annotation scopes (some discussion in https://jellezijlstra.github.io/pep695#other-issues).

Yeah, prohibiting yield/await makes sense to me. I don't know about walruses. Inside f-strings they create another class attribute, but that doesn't seem like a good thing to do here.

**Comment by lysnikolaou** [comment]
@davepeck Can you please a PR with your other approach, which I think is the way to go. This can probably be closed afterwards.

**Comment by davepeck** [comment]
@lysnikolaou sure thing; the new PR is #45. Thanks for humoring me on my first-ever cpython changes. :-)

**Pull request closed without merging**
